### ISSUE TITLE
Documentation: KAZILLIONS vs. inode limit

### ISSUE THREAD

**Issue by andresriancho** [AWNystrom/DiskDict#1]
While I like your implementation and code, I believe you should document a limitation in the implementation where you can't store more keys in the dict than the max number of files per directory that the file system imposes.

**Comment by AWNystrom** [comment]
Yes this is true. It depends on what file system you're using. I don't
think ext4 has any limits on that. I'll look into it and document it.
Thanks for the suggestion.

**Comment by andresriancho** [comment]
awesome :+1:

**Comment by andresriancho** [comment]
PS: A solution might be to hash the key (lets say the result is 4d5831c3de6feb69a6b150946753065c), and then create directories like this:

4d583/1c3de/6feb6/9a6b/150946753065c

Note the `/` where the hash is stored in "subdirs"

**Comment by AWNystrom** [comment]
Interesting idea, but if there are k sub-directories, wouldn't you have to store 1/k of the files that get hashed to that value in each subdirectory for this to have an effect? This could easily be done. In the top-most directory, have a file that says which of the k subdirectories a given key belongs in. This is determined at the time of storage sampling [1,k] uniformly. It would allow a factor of k more pairs to be stored. Unless the total number of files in a directory includes those stored in subdirectories.
